# Generated by Django 4.1.7 on 2023-04-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='user',
            new_name='author',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('blogs', models.ManyToManyField(related_name='tags', to='blogs.blog')),
                ('comments', models.ManyToManyField(related_name='tags', to='blogs.comment')),
            ],
        ),
    ]
