# Generated by Django 4.1.7 on 2023-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_user_like_author_rename_user_reaction_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Haha', 'Haha'), ('WOW', 'Wow'), ('SAD', 'Sad'), ('Angry', 'Angry')], max_length=10),
        ),
    ]
